# Generated by Django 5.2.3 on 2025-08-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Us',
        ),
    ]
