# Generated by Django 5.2.3 on 2025-08-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_delete_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(null=True),
        ),
    ]
