# Generated by Django 5.2.3 on 2025-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
