# Generated by Django 5.2.3 on 2025-08-29 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_smartphone_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Categoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.main_categoty')),
            ],
        ),
    ]
