# Generated by Django 5.2.3 on 2025-08-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_main_categoty_categoty'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='compare.categoty'),
        ),
    ]
