# Generated by Django 5.2.3 on 2025-10-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0009_product_acc_brand_product_brand_product_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
