# Generated by Django 5.2.3 on 2025-10-03 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='phones/')),
                ('amazon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flipkart_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('croma_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amazon_link', models.URLField(blank=True, null=True)),
                ('flipkart_link', models.URLField(blank=True, null=True)),
                ('croma_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='compare.categoty')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='phones/')),
                ('amazon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flipkart_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('croma_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amazon_link', models.URLField(blank=True, null=True)),
                ('flipkart_link', models.URLField(blank=True, null=True)),
                ('croma_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Laptop', to='compare.categoty')),
            ],
        ),
    ]
